sublist:
    label: 'mavitm.compon::lang.compon.sublist'
    view:
        list: $/mavitm/compon/models/mtmdata/subList.yaml
        toolbarButtons: create|delete
    manage:
        form: $/mavitm/compon/models/mtmdata/subForm.yaml
        recordsPerPage: 100
