title: Tab
modelClass: Mavitm\Compon\Models\Mtmdata
list: $/mavitm/compon/models/mtmdata/parentList.yaml
recordUrl: 'mavitm/compon/tab/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
