sublist:
    label: 'mavitm.compon::lang.compon.sublist'
    view:
        list: $/mavitm/compon/models/mtmdata/subimagesList.yaml
        toolbarButtons: create|delete
    manage:
        form: $/mavitm/compon/models/mtmdata/imgForm.yaml
        recordsPerPage: 100
