title: Menu
modelClass: Mavitm\Compon\Models\Menu
list: $/mavitm/compon/models/menu/parentList.yaml
recordUrl: 'mavitm/compon/menus/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

recordsPerPage: 50
showCheckboxes: true
showSetup: true

defaultSort:
    column: created_at
    direction: desc